services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbspringboot
      TZ: UTC
    # ❗ Recomendado: NÃO expor 3306 no host para evitar conflito com MySQL local.
    # Se você realmente precisar expor, troque para "3307:3306".
    # ports:
    #   - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s
    restart: unless-stopped

  api:
    image: loja-api:1.0
    build:
      context: ./springboot/demo
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dbspringboot?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      PORT: "8089"
      TZ: UTC
    ports:
      - "8089:8089"
    restart: unless-stopped

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  db_data:
