apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-quiz-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-quiz
  template:
    metadata:
      labels:
        app: postgres-quiz
    spec:
      securityContext:
        fsGroup: 999
      initContainers:
      - name: postgres-init
        image: busybox:1.36
        command: ['sh', '-c', 'chmod 700 /var/lib/postgresql/data && chown -R 999:999 /var/lib/postgresql/data']
        volumeMounts:
        - name: postgres-quiz-storage
          mountPath: /var/lib/postgresql/data
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5433
        args: ["-c","listen_addresses=*","-c","port=5433"]
        env:
        - name: POSTGRES_USER
          value: "meuusuario"
        - name: POSTGRES_PASSWORD
          value: "minhasenha"
        - name: POSTGRES_DB
          value: "meubanco"
        - name: PGPORT
          value: "5433"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        securityContext:
          runAsUser: 999
          runAsNonRoot: true
        volumeMounts:
        - name: postgres-quiz-storage
          mountPath: /var/lib/postgresql/data
        - name: quiz-init-sql
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
      volumes:
      - name: postgres-quiz-storage
        emptyDir: {}
      - name: quiz-init-sql
        configMap:
          name: quiz-sql-config
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-quiz-service
spec:
  type: NodePort
  selector:
    app: postgres-quiz
  ports:
  - protocol: TCP
    port: 5433
    targetPort: 5433
    nodePort: 30555
