apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-user
  template:
    metadata:
      labels:
        app: postgres-user
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5434
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "serverB"
        volumeMounts:
        - name: postgres-user-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-user-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-user-service # <-- E este é o nome para o segundo servidor!
spec:
  selector:
    app: postgres-user
  ports:
    - protocol: TCP
      port: 5434
      targetPort: 5434
